global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'agent-api-platform'
    scrape_interval: 5s
    metrics_path: '/v1/metrics'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
